//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exexexexexe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Susem_dbEntities : DbContext
    {
        public Susem_dbEntities()
            : base("name=Susem_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GGG_Brigada> GGG_Brigada { get; set; }
        public virtual DbSet<GGG_Brigadir> GGG_Brigadir { get; set; }
        public virtual DbSet<GGG_Prorab> GGG_Prorab { get; set; }
        public virtual DbSet<GGG_Rabochiy> GGG_Rabochiy { get; set; }
        public virtual DbSet<GGG_Stroi_Ob> GGG_Stroi_Ob { get; set; }
        public virtual DbSet<GGG_Users> GGG_Users { get; set; }
        public virtual DbSet<GGG_Zadanie_Brigadir> GGG_Zadanie_Brigadir { get; set; }
        public virtual DbSet<GGG_Zadanie_Rabochi> GGG_Zadanie_Rabochi { get; set; }
    }
}
