//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exexexexexe
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGG_Zadanie_Brigadir
    {
        public int ID { get; set; }
        public string Nazvanie { get; set; }
        public string Opisanie { get; set; }
        public Nullable<System.DateTime> Data_Naznacheniya { get; set; }
        public Nullable<System.DateTime> Data_Okonchaniya { get; set; }
        public string Status { get; set; }
        public Nullable<int> Brigadir { get; set; }
    
        public virtual GGG_Brigadir GGG_Brigadir { get; set; }
    }
}
